// ── CSS variable shorthands ────────────────────────────────────────────────
export const v = {
  base:          'var(--lx-base)',
  surface:       'var(--lx-surface)',
  surfaceRaised: 'var(--lx-surface-raised)',
  surfaceSunken: 'var(--lx-surface-sunken)',
  ink:           'var(--lx-ink)',
  ink2:          'var(--lx-ink-2)',
  ink3:          'var(--lx-ink-3)',
  inkInverse:    'var(--lx-ink-inverse)',
  border:        'var(--lx-border)',
  borderStrong:  'var(--lx-border-strong)',
  borderSubtle:  'var(--lx-border-subtle)',
  accent:        'var(--lx-accent)',
  accentDark:    'var(--lx-accent-dark)',
  accentDim:     'var(--lx-accent-dim)',
  accentText:    'var(--lx-accent-text)',
  error:         'var(--lx-error)',
  errorDim:      'var(--lx-error-dim)',
  errorText:     'var(--lx-error-text)',
  success:       'var(--lx-success)',
  successText:   'var(--lx-success-text)',
  scrim:         'var(--lx-scrim)',
  fontDisplay:   'var(--font-display)',
  fontBody:      'var(--font-body)',
  fontMono:      'var(--font-mono)',
};
